import type { GameDerivedState } from "@/lib/api";


export function derivedStateFixture(
  overrides: Partial<GameDerivedState> = {},
): GameDerivedState {
  return {
    projection_version: 1,
    projection_kind: "effective_event_projection",
    game_id: 1,
    through_logical_sequence: null,
    event_ledger_head_sequence: 4,
    effective_event_count: 4,
    last_applied_logical_sequence: 4,
    has_format_snapshot: true,
    is_rule_engine_result: false,
    format_snapshot_id: 2,
    format_key: "wolf_king_guard",
    format_name: "Wolf King Guard",
    snapshot_schema_version: 1,
    phase: {
      current_phase: "night",
      current_round_no: 1,
      phase_is_open: true,
      phase_started_event_id: 1,
      last_completed_phase: null,
      last_completed_round_no: null,
      last_completed_event_id: null,
      last_observed_phase: "night",
      last_observed_round_no: 1,
      last_observed_event_id: 4,
    },
    participants: [
      {
        participant_id: 1,
        user_id: 101,
        seat_number: 1,
        display_name_snapshot: "Player One",
        recorded_role_name: "Seer",
        recorded_faction: "good",
        is_active_in_game: true,
        has_exile_record: false,
        has_death_record: false,
        exile_event_ids: [],
        death_event_ids: [],
        exit_event_ids: [],
        first_exit_logical_sequence: null,
        latest_exit_logical_sequence: null,
      },
      {
        participant_id: 2,
        user_id: 102,
        seat_number: 2,
        display_name_snapshot: "Player Two",
        recorded_role_name: "Werewolf",
        recorded_faction: "wolf",
        is_active_in_game: false,
        has_exile_record: true,
        has_death_record: false,
        exile_event_ids: [4],
        death_event_ids: [],
        exit_event_ids: [4],
        first_exit_logical_sequence: 4,
        latest_exit_logical_sequence: 4,
      },
    ],
    sheriff: {
      badge_status: "held",
      current_sheriff_participant_id: 1,
      elected_event_id: 3,
      last_transfer_event_id: null,
      destroyed_event_id: null,
      current_candidate_participant_ids: [],
      withdrawn_participant_ids: [2],
      declaration_provenance: [{ participant_id: 1, event_ids: [2] }],
      withdrawal_provenance: [{ participant_id: 2, event_ids: [2] }],
    },
    ballots: [{
      vote_kind: "sheriff",
      round_no: 1,
      ballot_no: 1,
      vote_event_ids: [2, 3],
      vote_records: [
        {
          event_id: 2,
          voter_participant_id: 1,
          target_participant_id: 1,
          vote_weight: 1,
          logical_sequence_no: 2,
        },
        {
          event_id: 3,
          voter_participant_id: 1,
          target_participant_id: 2,
          vote_weight: 1,
          logical_sequence_no: 3,
        },
      ],
      abstention_records: [],
      voter_participant_ids: [1],
      duplicate_voter_participant_ids: [1],
      raw_tally: [
        { participant_id: 1, vote_weight: 1 },
        { participant_id: 2, vote_weight: 1 },
      ],
      computed_tally: null,
      tally_is_unambiguous: false,
      explicit_tie_records: [],
      revote_records: [],
      explicit_outcome_event_ids: [3],
    }],
    recorded_action_usage: [
      {
        participant_id: 1,
        recorded_seer_check_count: 1,
        recorded_witch_antidote_count: 0,
        recorded_witch_poison_count: 0,
        recorded_guard_protection_count: 0,
        recorded_hunter_shot_count: 0,
        recorded_wolf_king_shot_count: 0,
        recorded_wolf_self_explosion_count: 0,
        recorded_sheriff_vote_count: 2,
        recorded_exile_vote_count: 0,
      },
      {
        participant_id: 2,
        recorded_seer_check_count: 0,
        recorded_witch_antidote_count: 0,
        recorded_witch_poison_count: 0,
        recorded_guard_protection_count: 0,
        recorded_hunter_shot_count: 0,
        recorded_wolf_king_shot_count: 0,
        recorded_wolf_self_explosion_count: 0,
        recorded_sheriff_vote_count: 0,
        recorded_exile_vote_count: 0,
      },
    ],
    recorded_actions: [{
      event_type: "seer_checked",
      phase: "night",
      round_no: 1,
      actor_participant_id: 1,
      event_ids: [2],
      recorded_count: 1,
      latest_recorded_target_participant_id: 2,
    }],
    round_summaries: [{
      round_no: 1,
      phase: "night",
      event_count: 4,
      event_ids: [1, 2, 3, 4],
      phase_started_event_ids: [1],
      phase_completed_event_ids: [],
      night_resolved_event_ids: [],
      event_type_counts: [
        { event_type: "phase_started", count: 1 },
        { event_type: "seer_checked", count: 1 },
        { event_type: "player_exiled", count: 1 },
      ],
    }],
    night_resolutions: [],
    issues: [{
      code: "duplicate_vote_by_voter",
      severity: "warning",
      message_key: "projection.issue.duplicate_vote_by_voter",
      event_ids: [2, 3],
      participant_ids: [1],
      round_no: 1,
      phase: "day",
      details: { vote_kind: "sheriff", ballot_no: 1 },
    }],
    ...overrides,
  };
}
